public enum EBehaviourCore
{
	NONE = 0,
	USE_DEFAULT = 1,
	NO_CHANGE = 2,
	ATTACK_RANGED = 3,
	MOVE_WITHIN_RANGE = 4,
	MOVE_TO_TARGET = 5,
	ATTACK_MELEE = 6,
	MOVE_TO_POSIITON = 7,
	VCS_AT_NODE_DEFAULT = 8,
	VCS_TRAVERS_LINK_DEFAULT = 9,
	VCS_TRAVERS_LINK_WAIT_ON_THREAT = 10,
	RETURN_HOME = 11,
	NUM_BEHAVIOURS = 12
}
